/*

Copyright (C) 2012 ForeFire Team, SPE, Université de Corse.

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 US

*/

#ifdef _JNI_IMPLEMENTATION

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fprop_coupling_CCoupling */

#ifndef _Included_fprop_coupling_CCoupling
#define _Included_fprop_coupling_CCoupling
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fprop_coupling_CCoupling
 * Method:    executeCommand
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_fprop_coupling_CCoupling_executeCommand
(JNIEnv *, jclass, jstring);

/*
 * Class:     fprop_coupling_CCoupling
 * Method:    getMatrix
 * Signature: (Ljava/lang/String;)[[F
 */
JNIEXPORT jobjectArray JNICALL Java_fprop_coupling_CCoupling_getMatrix
(JNIEnv *, jclass, jstring);


/*
 * Class:     fprop_coupling_CCoupling
 * Method:    setMatrix
 * Signature: (Ljava/lang/String;[[F)V
 */
JNIEXPORT void JNICALL Java_fprop_coupling_CCoupling_setMatrix
  (JNIEnv *, jobject, jstring, jobjectArray);


#ifdef __cplusplus
}
#endif
#endif
#endif
